source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/project.pbxproj, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/AppDelegate.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ActivityUpdate.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Agenda.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/CalendarReminder.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ExpenseReport.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/FlightDetails.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/FlightItinerary.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/FlightUpdate.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/FoodOrder.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageGallery.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputForm.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Inputs.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Restaurant.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SimpleFallback.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SportingEvent.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/StockUpdate.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/WeatherCompact.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/WeatherLarge.json
Added tableView for AdaptiveCard Samples
=> Added tableView for Adaptive Card samples

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib
=> Wired sample json to render in Visualizer app

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift
=> Sample app tweaks - Added TextView to display JSON

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/QmlTag.cpp, source/qml/Library/RendererQml/QmlTag.h
=> Fix color property

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardItemDelegate.qml, source/qml/Samples/QmlVisualizer/main.cpp
=> Fix TextBlock Renderer

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/xcshareddata/xcschemes/ADCMacOSVisualizer.xcscheme
=> scheme fix

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputNumberSample.json, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift
Implementation of Input.Number Renderer for MacOS swift platform.
=> [macos] input number renderer

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
**Updating project pbxproj file for macOS input number renderer files**
=> [macos] updated project.pbxproj file

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/QmlTag.cpp, source/qml/Samples/QmlVisualizer/main.cpp
=> Qml Input text renderer

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputToggle.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputToggleRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputToggleRendererTests.swift
=> Input toggle wrap added

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/project.pbxproj, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/MainViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/cortana-skills-classic.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/cortana-skills-dark.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/cortana-skills-light.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/hostConfig1.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/hostConfig2.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/microsoft-teams-dark.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/microsoft-teams-light.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/outlook-desktop.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/render-to-image.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/sample.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/skype.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/testVariantHostConfig.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/webchat.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/webex_dark_config.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/webex_light_config.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/windows-notification.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/windows-timeline.json
**Host Config Integration for Visualizer App**
=> Mac ACL Visualizer - Host Config integration

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Samples/QmlVisualizer/main.cpp
=> Number Input Render

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h, source/qml/Samples/QmlVisualizer/main.cpp
=> RichTextBlock and TextRun for QML

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Samples/QmlVisualizer/main.cpp
=> Adding Toggle Input Renderer

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
=> fix upstream build

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/RenderedQmlAdaptiveCard.cpp, source/qml/Library/RendererQml/RendererQml.vcxproj, source/qml/Library/RendererQml/RendererQml.vcxproj.filters, source/qml/Samples/QmlVisualizer/SampleCardJson.h, source/qml/Samples/QmlVisualizer/main.cpp, source/qml/Samples/QmlVisualizer/samplecardlist.cpp
=> Syntax fix

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SeperationAndSpacingTest.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
Certain inherited properties like ID, isVisible, Seperator, Spacing working
=> Inherited properties

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/ADCMacOSVisualizer.entitlements, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputTextInlineAction.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift
Signed-off-by: rohshar6 <rohshar6@cisco.com>
Inline action added for input text
=> Inline action for input text

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/QmlTag.cpp, source/qml/Library/RendererQml/QmlTag.h, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
=> Code refactor

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
=> ACRButton Added

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputLabel.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
Signed-off-by: rohshar6 <rohshar6@cisco.com>
Added label property to input elements.
=> Adding label property to Input elements

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SampleColumnSet.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SampleColumnSetWeighted.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SampleTextBlock.json, source/macos/AdaptiveCards/.swiftlint.yml, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/xcshareddata/xcschemes/AdaptiveCards.xcscheme, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- Adds some functionalities of ColumnSet element
=> [MacOS] ColumnSet Renderer - Part 1

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/CardEditor.qml, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj.filters, source/qml/Samples/QmlVisualizer/SampleCardListView.qml, source/qml/Samples/QmlVisualizer/adaptivecard_dark_config.h, source/qml/Samples/QmlVisualizer/adaptivecard_light_config.h, source/qml/Samples/QmlVisualizer/samplecardmodel.cpp, source/qml/Samples/QmlVisualizer/samplecardmodel.h
- Added adaptivecard_light_config and adaptivecard_dark_config  files
- Added a dropdown to select theme
- Load card based on the theme selected
=> SPARK-215104: Addition of light and dark config

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h, source/qml/Samples/QmlVisualizer/SampleCardListView.qml
=> Fix theme and GetColor

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputDateSample.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputTimeSample.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputDateRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputTimeRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputTime.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputDateRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift
Created Date and Time Renderer for MacOS
Added Unit tests in file InputDateRendererTest and InputTimeRendererTest for testing.
=> Date and Time Renderer

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> ImageRender fix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h, source/qml/Samples/QmlVisualizer/SampleCardJson.h, source/qml/Samples/QmlVisualizer/samplecardlist.cpp
=> ColumnSet Renderer

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Samples/QmlVisualizer/SampleCardJson.h
=> Seperator for Columnset

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.h
Color fix for background and font color for following elements:
- TextInput 
- NumberInput
- ToggleInput
- ChoiceSet
- CheckBox
- DateInput
- TimeInput
- Container
=> SPARK-215934: Fix colors of elements

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/project.pbxproj, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/Application.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift
Added Main Menu to the Visualizer for edit properties to work.
=> Added Main Menu

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ContainerSample.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputTextInlineAction.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeContainer.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
Created Container Renderer with the following properties.
1. Styling
2. Minheight
3. VerticalContentAlignment
4. Spacing and basic card element properties
=> Container renderer PR

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
Fetching time and date format from user's system for Time and Date Renderer
**Time Format:**
12 hour format
24 hour format
**Date Format:**
dd/MMM/yyyy
yyyy/dd/MMM
yyyy/MMM/dd
=> Fetching time and date format from user's system for Time and Date Renderer

source/macos/AdaptiveCards/AdaptiveCards/Base/ACRImageProperties.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentHoldingView.swift
=> Image renderer constraints [mac]

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/SampleCardJson.h, source/shared/cpp/ObjectModel/CollectionTypeElement.cpp
=> ColumnSet Width Fix

source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.h, source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.mm, source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactTextField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/FactSetRendererTest.swift
=> Fact set markdown

source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift
page above.
Added hover over different input types such as toggle, choiceset, date, time, number and, text.
3. Manual scenario verification …
=> Add hover over Input fields

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
=> [MacOS] Button layout fixes

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
=> Button insets fix

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/Targets.swift, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionShowCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
=> Action.ShowCard Renderer Part-1

source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift
=> [MacOS] Action width anchor adjust

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift
Signed-off-by: rohshar6 <rohshar6@cisco.com>
1. Added fix for dark theme
=> Dark theme fix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> Fixed wrap & elide property for Toggle Input

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/webex_dark_config.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/hostconfigs/webex_light_config.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionsRendererTests.swift
1. Wrap action inside actionSet
2. Updated hostconfig for webex light & dark theme
3. Added test cases for Actions
=> [Mac] Actions wrap inside Action Set

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
page above.
- InputDate now displays date in MediumFormat (eg: 19-Mar-2020)
System date format is fetched if the System Date is in any one of the following formats:
dd-MM-yyyy  or dd-MMM-yyyy
MM-dd-yyyy or  MMM-dd-yyyy
yyyy-MM-dd or yyyy-MMM-dd
yyyy-dd-MM or yyyy-dd-MMM
dd-> day (eg: 19)
MM-> month( eg: 01)
MMM-> month (eg: Jan)
yyyy-> year (eg: 2021)
- The selected …
=> Date medium format

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ShowCardMultiple.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/Targets.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionShowCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeAdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeShowCardAction.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionShowCardRendererTests.swift
- Added ShowCard Action support
- Used background color from hostConfig
- Persisted inputs inside showcards 
=> Show card action

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h, source/qml/Samples/QmlVisualizer/SampleCardJson.h, source/qml/Samples/QmlVisualizer/samplecardlist.cpp
=> Showcard part 2

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeOpenURLAction.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionOpenURLRendererTests.swift
=> [MacOS] Action OpenURL completion

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
1. Added positive, destructive and default style to Action Button
=> [Mac] Action Style for Action Button

source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift
=> [MacOS] Image width fix

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRBackgroundImageView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionOpenURLRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/BackgroundImageViewTests.swift
Redeclaration in OpenURLTest Fixed
page above.
At the very least please describe the issue you are addressing, …
=> Background Image Wiring Done

source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeChoiceSetInput.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumnSet.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputTime.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputToggle.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextInput.swift
1. Added getId and getVisible properties to fake elements
=> [Mac] Added fix for fake elements for test cases

source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift
- Added Inherited properties support for Column elements
=> [MacOS] Column Inherited Properties

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
Date and time pop-over updation
=> Date and time pop-over updation

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
- Changed the separator between day, month an year in InputDate to "/" from "-"
- Fix for the placeholder bug where placeholder does not reappear once the Input Date or Input Time gains focus 
Input Date 
https://user-images.githubusercontent.com/78541663/112466227-a0a3ec00-8d8b-11eb-8d46-3801900a4d42.mp4
How you verified the fix, including one or all of …
=> Placeholder Fix for Input Date and Input Time

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> Textblock bugs

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
=> [SPARK-221254] - Color of Column in Select Action after Hovering

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Utils/BundleUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactTextField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/BackgroundImageViewTests.swift
=> Refactoring Done and Constants Removed

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/samplecardmodel.cpp
=> Input number

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SelectActionColumn.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/SelectActionHandlingProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentHoldingView.swift
page above.
Working selectAction for the above elements
On click "We support Colors"
=> SelectAction for TextRun and Images

source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/BackgroundImageViewTests.swift
Fix for `Submit Action` in nested `ShowCard` setup. 
=> [MacOS] SubmitAction fix for Nested Show Card setup

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib
Added Scroller to the card view
=> [MacOS]Added scroller to the card view

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImagesInheritedProperties.json, source/macos/AdaptiveCards/AdaptiveCards/Base/ACRImageProperties.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentHoldingView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeImage.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageRendererTests.swift
* Image rendering fixes to support visibility toggle 
* Other rendering fixes
=> image renderer properties [mac]

source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift
=> [MacOS] FactSet Alignment fix

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib
=> [MacOS]Background Color Fix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Samples/QmlVisualizer/SampleCardJson.h, source/qml/Samples/QmlVisualizer/samplecardlist.cpp
=> Bleed Fix for container and columnset

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> Image width fix

source/qml/Library/RendererQml/Utils.cpp
=> InputTime fix for Linux

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/Utils.cpp
=> Showcard bugs

source/qml/Library/RendererQml/Utils.cpp
=> Fixed error for Linux Build (InputTime)

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnInheritedProperties.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetContainer.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumnSet.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeImage.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeRichTextBlock.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift
=> [MacOS] ColumnSet Height wrapping fixes

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/TestUtils.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetAlignment.json
=> [MacOS] Enabling pre-known dimensions cases for ResourceResolver

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h, source/qml/Samples/QmlVisualizer/SampleCardJson.h
=> Background Image fillmode property fix

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Managers/RendererManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/UnknownElementRenderer.swift
Added Fallback Property to All elements
FallBack With Drop and TextBlock
FallBack With ActionSet
Fallback with Input Element
TextBlock with ellipses
=> [MacOS]Added Fallback

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetWithEmptyColumn.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
Fixed label color property being too light
Fixed button title property so it doesn't extend beyond card
Changed Action.Submit to maintain Parity with Windows
Button Title
Button with both iconURL and chevron
Submit Action Parity
=> [MacOS]Minor fixes for buttons and Submit Action

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
=> Time Input renderer placeholder text fix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
=> Bleed Width and Height

source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.mm, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift
=> [MacOS] Some minor attribute fixes to textblock

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
=> [MacOS] Column width edge case fixes

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/project.pbxproj, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/Utils.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ActionSetSample.json, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionOpenURLRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionShowCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionSubmitRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
=> [MacOS]Button Style Fix 

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/QmlTag.cpp, source/qml/Library/RendererQml/QmlTag.h
=> Clean Escaped Quotes

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputTimeRenderer.swift
=> [MacOS] Method name change

source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
1. Added Fix for collection items for ambiguous behaviour
2. Updated Bleed with padding fix
=> [MacOS]Collection Items fix and Bleed update

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift
=> [MacOS] Input number fix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> Clean comments

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Samples/QmlVisualizer/AdaptiveCardItemDelegate.qml, source/qml/Samples/QmlVisualizer/CardContent.qml, source/qml/Samples/QmlVisualizer/main.cpp, source/qml/Samples/QmlVisualizer/main.qml
=> Resize bug fix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
=> Fix overlay error

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
=> Added show card callback

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
page above.
Runtime error when Minimum and Maximum Date is not passed in "yyyy-mm-dd" format
Fixed by Adding a function to validate the inputted date 
How you verified the fix, …
=> Fix Input Date RunTime Error

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
=> Graphicsfix

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
=> Handled the Invalid Qml Ids

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/xcshareddata/xcschemes/ADCMacOSVisualizer.xcscheme, source/macos/AdaptiveCards/AdaptiveCards-bridge/AutoGenerated/Models/ACSParseResult.mm, source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeConverter.mm, source/macos/AdaptiveCards/AdaptiveCards/Utils/BundleUtils.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionOpenURLRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionSubmitRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
=> [MacOS] Invalid JSON exception fixed

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
Fixed the invalid month displayed for Input Date
Fixed the invalid signal names used in Input Date
Before
After
3. Manual …
=> Fix Invalid Month for Input Date

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/Views/FakeRootView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionOpenURLRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionSubmitRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/FactSetRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/RichTextBlockRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextBlockRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
=> [MacOS] Resolve HTML Text callback Added

source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift
Fixed bug which allowed multiple text blocks to have text selected from at the same time.
Old card:
Existing relevant unit/regression tests that you ran
=> Fixed multiple selection issue

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
Redesigned the Dropdown Menu in Input ChoiceSet
Light Mode
Dark Mode
3. Manual scenario verification if any; ***Do include .gif's …
=> [SPARK-242277] Redesgin Dropdown Menu in InputChoiceSet (Windows)

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
Converted the dropdowns of Input Date and Input Time to popups
3. Manual scenario verification if any; ***Do include .gif's or …
=> [SPARK-237834] Popup fix for Input Date and Time (Windows)

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/Utils.cpp
=> [SPARK-244835] Bug Fix for Input ChoiceSet (Windows)

source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
=> [MacOS] Added changes to maintain parity with webex

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ImageUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ImageSetImageViewTests.swift
=> [MacOS] ShowCard hides ImageSet fix

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
=> [MacOS] Removed isHidden validation on InputHandlers

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnVisibility.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift, source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp, source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp, source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.h
=> [MacOS] Newline Support & Column isVisible update

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/MultiLineInputTextViewTests.swift
=> [MacOS]Working input number rendered

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> [Win] Cards accessibility

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/Utils.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/HostConfigUtilsTests.swift
=> [Macos] Fixed text alignment issue and changed color scheme to argb from rgba

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
page above.
Usage of the adaptive card MarkdownParser to convert it to richText
3. Manual scenario verification if any; ***Do include .gif's …
=> [SPARK-278935] Fix TextBlock Markdown (Windows)

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h, source/qml/Samples/QmlVisualizer/samplecardmodel.cpp
page above.
* Last Show Card's Radius Changed
* Check mark color Changed in Dark Mode
* Input fields aligned to center
* Action Buttons Text Fixed along with Specs
* Calendar and Date Picker Focus Color Changed
If appropriate, please include a link to a card in one of the …
=> [Win]Buttons and Cards UI Rebrand Bug Fixes

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h, source/qml/Samples/QmlVisualizer/samplecardmodel.cpp, source/qml/Samples/QmlVisualizer/samplecardmodel.h
page above.
* Added Accessibility Role Descriptions for Buttons and Cards
* Changed Main Card border color
1. New unit tests that were added if any. If none were added please add a quick line explaining why …
=> [Win] Accessibility for Screen Reader and Keyboard

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
[SPARK-275613](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-275613) : Crash when using fallback  
3. Manual scenario …
=> SPARK-275613 : Crash when using fallback

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputDateRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift
=> [MACOS] Accessibility Fixes in Cards

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
page above.
* Input elements height fixed for stretch property [SPARK-226794](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-226794)
* Links Accessibility inside cards improved [SPARK-289083](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289083)
If appropriate, please …
=> [Win]Stretch Input Elements Height Fix

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/AssociatedInputs.json, source/macos/AdaptiveCards/AdaptiveCards-bridge/AutoGenerated/Models/ACSSubmitAction.mm, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/Targets.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRActionSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/Views/FakeRootView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionSubmitRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRActionSetViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
=> [MacOS]Add Support for Associated Inputs in Action.submit

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h
page above.
* Added person style for images
* Images clipping fixed
* Fact set height in stretch fixed
At the …
=> [Win] Image Person Style

source/qml/Library/RendererQml/NumberInputRender.cpp, source/qml/Library/RendererQml/TextInputRender.cpp
page above.
SPARK-297239 : Unit Test Issues for Input Number and Input Text
2. Existing relevant …
=> SPARK-297239 : Unit Test Issues for Input Number and Input Text

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h, source/qml/Library/RendererQml/DateInputRender.cpp, source/qml/Library/RendererQml/TimeInputRender.cpp, source/qml/Samples/QmlVisualizer/samplecardmodel.cpp
page above.
- Fixed Show Card Validation bug
- Fixed Input Date and Input Time colors
At the very least please …
=> [Win] Validate Show Card Parent Input Elements 1.3

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ViewUtils.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift
=> [MAC] - Bug fix for number input not clearing error on keyboard accessibility on stepper

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/TestHelpers.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRInputTextViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
=> [MAC] - ScreenReader support on submit of cards with error message

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputDateRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputTimeRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputDateRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextInputRedererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRInputTextViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
=> [MAC] - Voiceover support for 1.3 schema in textfield and related inputs

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ErrorMessagesInCard.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/MultilineInputTextRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRInputTextViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/MultiLineInputTextViewTests.swift
=> [MAC] - Accessibility Fixes for Multiline Input, and other minor improvements

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/CheckBoxRender.cpp, source/qml/Library/RendererQml/CheckBoxRender.h, source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Library/RendererQml/ChoiceSetRender.h, source/qml/Library/RendererQml/ComboBoxRender.cpp, source/qml/Library/RendererQml/ComboBoxRender.h, source/qml/Library/RendererQml/DateInputRender.cpp, source/qml/Library/RendererQml/DateInputRender.h, source/qml/Library/RendererQml/NumberInputRender.cpp, source/qml/Library/RendererQml/NumberInputRender.h, source/qml/Library/RendererQml/TextInputRender.cpp, source/qml/Library/RendererQml/TextInputRender.h, source/qml/Library/RendererQml/TimeInputRender.cpp, source/qml/Library/RendererQml/TimeInputRender.h, source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Library/RendererQml/ToggleInputRender.h
page above.
* Fixed Action Submit render when 1.3 is disabled
* Text Input Submit JSON fixed …
=> [Win]1.3 Minor Bug fixes

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/CheckBoxRender.cpp, source/qml/Library/RendererQml/ComboBoxRender.cpp, source/qml/Library/RendererQml/ComboBoxRender.h, source/qml/Library/RendererQml/DateInputRender.cpp, source/qml/Library/RendererQml/DateInputRender.h, source/qml/Library/RendererQml/NumberInputRender.cpp, source/qml/Library/RendererQml/NumberInputRender.h, source/qml/Library/RendererQml/TextInputRender.cpp, source/qml/Library/RendererQml/TextInputRender.h, source/qml/Library/RendererQml/TimeInputRender.cpp, source/qml/Library/RendererQml/TimeInputRender.h, source/qml/Library/RendererQml/Utils.cpp, source/qml/Library/RendererQml/Utils.h
page above.
As of now including escape characters inside placeholders for input elements were leading to card not being renderer. This PR fixes the issue for all the Input elements and takes care of the accessibility
Input Toggle
Input Text
Input Number
Input Date
Input Time
Combobox
1. New unit tests …
=> [Win] : Escape Sequence in PlaceHolders

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Library/RendererQml/DateInputRender.cpp, source/qml/Library/RendererQml/NumberInputRender.cpp, source/qml/Library/RendererQml/TextInputRender.cpp, source/qml/Library/RendererQml/TimeInputRender.cpp, source/qml/Library/RendererQml/ToggleInputRender.cpp
page above.
* Fixed Crash due to empty Fact Set
* Hidden Input Values submission corrected
1. New unit tests that were …
=> [Win] : Crash Due to Empty Fact Set

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h, source/qml/Library/RendererQml/CheckBoxRender.cpp, source/qml/Library/RendererQml/CheckBoxRender.h, source/qml/Library/RendererQml/ChoiceSetRender.cpp
page above.
Added markdown support for ChoiceSet MultiSelection, ChoiceSet Expanded View, Action Toggle
If …
=> [Win] Markdown Support in Choice Set Expanded Style and Input Toggle

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactSetView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/FactSetRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRActionSetViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRButtonTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRChoiceSetButtonTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRChoiceSetViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRInputTextViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRTextFieldTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/BackgroundImageViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ImageSetImageViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/MultiLineInputTextViewTests.swift
Fix crash on webex related to factset not being initialised and added tests on acl
Tested on Webex for further crashes
=> added tests and fix

source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.h, source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.mm, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ChoiceSetInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputToggleRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRHyperLinkTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ChoiceSetInputRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputToggleRendererTests.swift
The issues fixed with this PR [SPARK-306189](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-306189).
page above.
- Fixed Markdown URL in input choice and input toggle.
- Fixed Wrap
Original             	   |  Updated
Wrap: True <img width="446" alt="Screenshot 2022-05-24 at 12 10 46 PM" src="https://user-images.githubusercontent.com/105660080/169965355-586792d5-db60-4d4c-bf79-c95f73fb8637.png"> | Wrap: True<img width="356" alt="Screenshot 2022-05-30 at 3 41 44 PM" src="https://user-images.githubusercontent.com/105660080/170970754-040c12c8-0d13-48d2-a706-ffe8fbd7b4cc.png">
Wrap: False<img …
=> Spark 306189 :: Input.ChoiceSet with markdown URL set in choice "title" appears as raw text.

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/RendererQml.vcxproj, source/qml/QmlRendererUnitTest/QmlRendererUnitTest.vcxproj, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj, source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel.vcxproj
=> Fix columns min height property

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
toggle visibility - column overlap render issue
when an item is toggled , it is not checked that other items spacing will be affected by this new item visibility causing overlap.
Old behaviour:
New behaviour:
`
{
"type":"AdaptiveCard",
"$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
"version":"1.2",
"body":[
{
"type":"ColumnSet",
"columns":[
{
"type":"Column",
"width":"stretch",
"items":[
{
"type":"TextBlock",
"text":"Column 1",
"wrap":true
}
],
"style":"attention",
"id":"column1"
},
{
"type":"Column",
"width":"stretch",
"items":[
{
"type":"TextBlock",
"text":"Column 2",
"wrap":true
}
],
"style":"attention",
"id":"column2"
},
{
"type":"Column",
"width":"stretch",
"items":[
{
"type":"TextBlock",
"text":"Column 3",
"wrap":true
}
],
"style":"attention",
"id":"column3"
}
], …
=> toggle visibility - column overlap render issue

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ToggleVisibilityChildToParent.json, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/TestHelpers.swift
Toggle Visibility from child card to Main Card does not work
`{
"type": "AdaptiveCard",
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.2",
"body": [
{
"type": "ColumnSet",
"columns": [
{
"type": "Column",
"width": "stretch",
"items": [
{
"type": "TextBlock",
"text": "Column 1",
"wrap": true
}
],
"style": "attention",
"id": "column1"
},
{
"type": "Column",
"width": "stretch",
"items": [
{
"type": "TextBlock",
"text": "Column 2",
"wrap": true
}
],
"style": "attention",
"id": "column2"
}
],
"style": "good",
"id": "columnSet"
}
],
"actions": [
{
"type": "Action.ToggleVisibility",
"title": "Column Set",
"targetElements": [
"columnSet"
]
},
{
"type": "Action.ToggleVisibility",
"title": "Column 1",
"targetElements": [
"column1"
]
},
{
"type": …
=> Toggle from child card to parent card

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
Action Submit's Data part may contain special characters. Json.Parse function was throwing an …
=> Special Character Support on Data JSON

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ACSFillerSpaceManagerTests.swift
This changes is part of Introducing Height Property.
This manager helps for stretchable view handling.
Add test case for ACSFillerSpaceManager
Most of properties are not affect by this changes. small change in behaviour will handle laterally.
page above.
Create a [descriptive …
=> ACSFillerSpaceManager Integration

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ACSFillerSpaceManagerTests.swift
This changes is part of Introducing Height Property.
This manager helps for stretchable view handling.
Add test case for ACSFillerSpaceManager
Most of properties are not affect by this changes. small change in behaviour will handle laterally.
page above.
Create a [descriptive …
=> Height Property : ACSFillerSpaceManager Integration

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-multi-bgimage-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-multi-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-multi-level-auto-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-multi-level-empty-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-multi-level-stretch-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-with-multi-textblock-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Textblock-multi-auto-height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Textblock-multi-height.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContainerView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeContainer.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextBlockRendererTests.swift
Support Height property at container view
Support Height property at TextBlock (we need some element which we can check with container)
Introduce new ACRContainerView Class
Remove Cycle Hierarchy from Main card render
Remove Cycle Hierarchy from Container render
Introduce intrinsicContentSize layout
Add Height test cases for Container, TextBlock
Most of properties are not affect by this changes. small change in behaviour will handle laterally.
the issues fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one if reasonable …
=> Height Property: Container, Textblock

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ImageRender.qml
=> Image's Height and Accessibility

source/qml/Library/RendererQml/ComboBoxRender.cpp
=> Combobox Initial Value fixed

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Library/RendererQml/DateInputRender.cpp, source/qml/Library/RendererQml/NumberInputRender.cpp, source/qml/Library/RendererQml/TextInputRender.cpp, source/qml/Library/RendererQml/TimeInputRender.cpp, source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ImageRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/RichTextBlockRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/SeparatorRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
=> [Win] Card toggle visibility

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ActionSet-Height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/FactSet-Height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputDate-Height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputNumber-Height.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputTime-Height.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputDateRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputTimeRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ViewUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRActionSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeActionSet.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeFactSet.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputTime.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionSetRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/FactSetRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputDateRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRActionSetViewTests.swift
- Changes and refactor at  FactSet, ActionSet and Inputs Number, Date, Time
- Remove cycle hierarchy layer
- Add Test case
page above.
This …
=> Support Height at ActionSet, FactSet, Inputs(Number, Date, Time)

source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetCompactPopupButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCompactChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRInputToggleView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRSingleLineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextInputView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeChoiceSetInput.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputTime.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputToggle.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextInput.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/TestHelpers.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- Support multiple error and label message with single context
- add test for height
page above.
This information lives with the code and will help …
=> Fix multiple error and label message for 1.3

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputDateRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputTimeRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRInputErrorTextField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRInputLabelTextField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRSingleLineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRInputLabelTextFieldTests.swift
- Input element with Label message. set that input initially hidden, but corresponding label should not hide.
- first view set to hide, second view doesn't hide there corresponding separator/padding view.
**Before**    |  **Updated**
page above.
Create a [descriptive title and provide all of the relevant …
=> Fix :: Error & Label Hide issue Padding view issue

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSVisibilityManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ACOVisibilityContext.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCompactChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRSingleLineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- ACRView retain in the memory that may create some bad access crashes.
- Fix dependancy injection, refactor variable allocation.
- make ACRView weak reference.
page above.
**** | **Before Memory Allocations**    |  **After Memory Allocations**
:-------------------------:|:-------------------------:|:-------------------------:
**Initial allocation** | <img …
=> Fix : Memory Allocation fixes

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift
checkbox and radio button not proper on extended screen
updated image scaling for ACRChoiceBUtton
old screenshot:
new screenshot
=> extended dislay issue

source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
=> [SPARK-371683]: Buttons and Cards - Specific card causes both Windows and Mac Webex client to become unresponsive

source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
=> change to unsigned int

source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRActionSetView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionSetRendererTests.swift
- Fix horizontal alignment issue with sub stackview. 
- Refactor naming convention.
- minor changes
page above.
This information lives with the code and will help future readers (***including yourself***) and will serve as …
=> Fixed: ActionSet Horizontal alignment issue

source/qml/Library/RendererQml/TextInputRender.cpp
page above.
Regex Match for 1.3 Card Fixed
At the very least please describe the issue you are addressing, and …
=> Regex Match Fixed

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardConstants.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/ThemeUtils.js, source/qml/Samples/QmlVisualizer/CardEditor.qml, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj.filters, source/qml/Samples/QmlVisualizer/main.cpp, source/qml/Samples/QmlVisualizer/qml.qrc, source/qml/Samples/QmlVisualizer/samplecardmodel.cpp, source/qml/Samples/QmlVisualizer/samplecardmodel.h
=> Adding Card Constants

source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h, source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Library/RendererQml/ToggleInputRender.h, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardConstants.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomCheckBox.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ToggleInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/ThemeUtils.js, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj, source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj.filters, source/qml/Samples/QmlVisualizer/main.cpp, source/qml/Samples/QmlVisualizer/qml.qrc
=> Initial changes

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSet-with-container-empty.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/HiddenInputElementWithLabel.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ToggleVisibilityInitiallyOffStretcableViews.json, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSVisibilityManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContainerView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextInput.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
* Fix issue where elements would not get proper spacing when they were initially hidden and then toggled visible
* Fix issue where container would take spacing even when it was completely empty and had no elements
* Fix issue where input label and error messages were hidden but were still increasing height of card
Case 1
`{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"actions": [
{
"title": "OK",
"type": "Action.Submit"
}
],
"body": [
{
"errorMessage": "error message error message error message error message ",
"height": "stretch",
"id": "1",
"isRequired": true,
"label": "Hello this is label",
"type": "Input.Date",
"isVisible": false
},
{
"errorMessage": "error message error message error message error message ",
"height": "stretch",
"id": "3",
"isRequired": true, …
=> [MAcOS]Fix bugs related to height properties

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/TestUtils.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet Test 1.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet Test 2.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet Test 3.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet Test 4.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Utils/ACSCollectionViewAlignLayout.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionViewItem.swift
Fixes:
- Add new FlowLayout Class
- Adaptive CollectionView item size with explicitly Height, Width and default sizing.
- Customised Vertical item position
- Customised Horizontal Item Position
- padding added from hostConfig
- add minimumInteritemSpacingForSectionAt, minimumLineSpacingForSectionAt
page above.
Create a [descriptive title and provide all of the …
=> commit: Add CollectionView FlowLayout

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/AppDelegate.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/TestUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ImageUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRImageWrappingView.swift
- change card size
- add item in testutils
- fix Aspect fit issue
page above.
This information lives with the code and will help future readers …
=> Aspect Fit in imageset item view

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetWidthInContainer.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetWidthInContainerRecursive.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
* Column Width now works when columnset inside other collection elements
* Removed need for padding when container is empty
| Original | Fixed
| --- | --- |
| ![Screenshot 2022-12-01 at 7 46 29 PM](https://user-images.githubusercontent.com/78855675/205083867-6a232587-d114-4d23-b339-ae7fe802dc45.png) | <img width="351" alt="Screenshot 2022-12-01 at 7 46 48 PM" src="https://user-images.githubusercontent.com/78855675/205083989-e5409b92-b35f-4c8c-9edd-5731713cb139.png"> |
| ![Screenshot 2022-12-01 at 7 46 00 PM](https://user-images.githubusercontent.com/78855675/205084161-86e64790-6a23-4703-baae-49afc29e7baa.png) | <img width="351" alt="Screenshot 2022-12-01 at 7 45 50 PM" src="https://user-images.githubusercontent.com/78855675/205084234-7984b2c7-7d1b-40f5-a256-78ad53248356.png"> |
How you …
=> Fixed width property in content stack view

source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardGenericTextElement.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomCheckBox.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomRadioButton.qml
=> Choice Set Binding Loop Fixed

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardGenericTextElement.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomCheckBox.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomRadioButton.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
=> Card JS functions Refactor

source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCompactChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeImageset.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRCollectionViewTests.swift
=> Mac B&C: Add ImageSet Unit Test

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet-Height-Auto.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet-Height-Stretch.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSet-pixl-Height-Stretch.json, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeImageset.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageSetRendererTests.swift
- Add Height support
- Unit test
- Remove Height support elements bool
- Update BaseCardElement Renderer
** ** | **Before**    |  **After**
:-------------------------:|:-------------------------:|:-------------------------:
Both Height = auto | <img width="451" alt="Screenshot 2022-12-19 at 9 55 57 AM" src="https://user-images.githubusercontent.com/105660080/208415304-59f917dc-2fef-4a69-9c76-bfc27ac951fa.png"> | <img width="447" alt="Screenshot 2022-12-19 at 9 54 23 AM" src="https://user-images.githubusercontent.com/105660080/208415373-837b9931-b222-4784-ac05-84f9090928f6.png">
Both Height = stretch | <img width="448" alt="Screenshot 2022-12-19 at 9 56 10 AM" src="https://user-images.githubusercontent.com/105660080/208415314-c3cf09a9-9ea6-4bd1-92e8-e7f0ac538a15.png"> | <img width="444" …
=> ImageSet : Add ACSHeightType Support

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/CompactChoiceSetToolTip.json, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetCompactPopupButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCompactChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ChoiceSetInputRendererTests.swift
Added tooltip for compact choiceset
Added tests
=> Added tooltip for choiceset

source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Library/RendererQml/Utils.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/InputLabel.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
=> Input Action Submit Fix

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/column-internal-stretch.json, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
fix :
- ColumnSet height is stretch
- add support Internal element height does not stretch in center/bottom vertical alignment
- test case
page above.
Create a [descriptive title and provide all of the relevant details in the description](https://chris.beams.io/posts/git-commit/). …
=> fix Column stretch, add support vertical content alignment

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/RichTextBlockSample.json, source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.mm, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/RichTextBlockRendererTest.swift
- update RichTextBlockRenderer
- update Parser
page above. …
=> RichTextBlockRenderer Markdown Parser changes

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/TextInputRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/AdaptiveActionRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/DateInputPopout.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ImageRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/RichTextBlockRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/TextInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/TimePickerListView.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
page above.
- Validation for Input Elements should not be done if Associated Inputs is given as "auto", But …
=> Action.Submit Associate Input FIx

source/qml/Samples/QmlVisualizer/AdaptiveCardQml/AdaptiveActionRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
=> Associate Input Submit Fix

source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ToggleInputRender.qml
=> SPARK-407820

source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputDateRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift
- ACRDateField Focus style changes
- ACRTextField Focus style changes
- add Test
page above.
This information lives with the code and will help future …
=> Redesign Accessibility focus style Date-time picker

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/Targets.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRActionSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/Views/FakeRootView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ActionOpenURLRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextBlockRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRActionSetViewTests.swift
- update ACRTextView with new hyperlink dataset
- add new testcase
page above.
At the very least please …
=> Hyperlink accessibility in TextBlock

source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift
fix space key down event
page above.
At the very least please describe the issue you are addressing, and what …
=> update input render

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSelectActionFocus.json, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionViewItem.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRImageWrappingView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRCollectionViewTests.swift
- padding in imageset cell item
- focus in imageView
- add test
**Original** | **Updated**
page above.
This information lives with the code and will help future readers …
=> Visual focus at Image, ImageSet

source/qml/Library/RendererQml/ToggleInputRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardConstants.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ChoiceSetRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/DateInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/MultiLineTextInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/NumberInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/SingleLineTextInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/TextInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/TimeInputRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ToggleInputRender.qml
page above.
- Removed red background color from text fields when validation fails
- Show Error Message icon …
=> Cards Bug Fixes for Focus Rings

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ImageRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
page above.
- Center Alignment in Action Set Fixed
- …
=> Center align action set

source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/RichTextBlockRendererTest.swift
- add focus
- test case
page above.
At the very least please describe the issue you are addressing, and what …
=> macOS | Visual Focus Style | RichTextBlock

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/project.pbxproj, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/AppDelegate.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/Application.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/Scripts/verify-swiftlint.sh
Added a shortcut to render cards quickly in visualiser
Changed SwiftLint Script to get path from m1 mac
Upgraded min supported macos version to be same as Webex
=> Minor Usability changes

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetSelectAction.json, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ContainerSelectAction.json, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageRendererTests.swift
- add changes in ACRContentStackView
- add Test
page above.
At the very least please describe the issue you …
=> Implement blue focus ring for Container element with action

source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/FactSetRendererTest.swift
- update factset renderer
- test
page above.
At the very least please describe the issue you are addressing, …
=> [macOS] Implement blue focus ring for Fact Set

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
**Before output** | **Changes output**
page above.
At …
=> Fixed: Data field getting formatted while submitting

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRActionSetView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRActionSetViewTests.swift
- add changes
page above.
This information lives with the code and will help future readers (***including yourself***) and will serve as …
=> [macOS] Fix: Action not proper align in column

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
- Added Focus Ring to the whole Adaptive Card
- Jira : …
=> Focus Ring for Cards

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- add changes in ACRContentStackView
page above.
At the very least please describe the issue you are …
=> Fix : Space KeyDown not work in Buttons and Action button

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
- add changes in ACRDateField
page above.
At the very least please describe the issue you are addressing, and …
=> fix: Large focus ring around input element

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageSetActionToggle.json, source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ImageUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Utils/ViewUtils.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetCompactPopupButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionViewItem.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactSetView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeImage.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageSetRendererTests.swift
- refactor logic for find view in ViewUtils
- change in ACRCollectionView for support hide cell
- update identifier logic
- update test case
**Before**
**Update**
page above.
This information lives with the code and will help future …
=> MacOS | fix: Support Action toggle functionality At imageset

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/AssociatedInputInSelectAction.json, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/RichTextBlockRendererTest.swift
Fixed issue relating to associated input
https://app.vidcast.io/share/d9d388ae-67f2-42d2-b09b-9329cbbee7a3
Tests added
=> Fixed associated input issue

source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
=> Fix: [mac] Date-Time Picker Opens When Not Clicking On Time Field

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSAccessibilityFocusManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputDateRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputTimeRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRSingleLineInputTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/FactSetRendererTest.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageSetRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- Design and Develop Manager Class & Protocol
- Implement focus manager Logic for root view
- Implement focus protocol at Input[.Date, .Time, .Number, .Text] (ACRTextField)
- implement focus protocol at RichTextBlock, TextBlock, FactSet (ACRTextView)
- Implement key view setup logic
page above.
Create a [descriptive title and provide all of the …
=> [macOS] Focus Accessibility: Design Implement a Accessibility Focus Manager & Protocol

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/Application.xib, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.xib, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ChoiceSetInputRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputToggleRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCompactChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContainerView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRInputToggleView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputToggleRendererTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRChoiceSetViewTests.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- Implement focus manager logic at containers
- Implement focus protocol at Input.Toggle, ChoiceSet
- Implement key view setup logic
- Create unit test
- update app layout
- update shortcut, add new accessibility shortcuts
the issue fixed with this PR (eg …
=> [macOS] Focus Accessibility: Implement manual KeyView focus at containers

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/AdaptiveRenderContext.cpp, source/qml/Library/RendererQml/AdaptiveRenderContext.h
=> Vertical Alignment for Columns and Containers

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> Vertical Alignment for Cards

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift, source/macos/AdaptiveCards/AdaptiveCards/Base/Targets.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputToggleRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRActionSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactSetView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/Views/FakeRootView.swift, source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRActionSetViewTests.swift
- make new delegate method for get callback on action
- change open url action delegate
- change text view open url logic
- test
in issue …
=> Add action event delegate

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/Utils/AdaptiveCardUtils.js
=> Stretch Height and Bleed Refactor

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
=> Show Card Height Fixed

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp, source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
=> Submit Action Refactor

source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer.xcodeproj/project.pbxproj, source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift, source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj, source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift, source/macos/AdaptiveCards/AdaptiveCards/Managers/QueryManager.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift, source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
=> [mac]Added mock data to support typeahead later

source/qml/Samples/QmlVisualizer/AdaptiveCardQml/FilteredChoiceSetRender.qml
=> NoSearchFilter

source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ChoiceSetRender.qml, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/FilteredChoiceSetRender.qml, source/qml/Samples/QmlVisualizer/JSONSamples/ChoiceSetRenderFiltered.json, source/qml/Samples/QmlVisualizer/main.cpp
=> [Win] - Multiselect tile implemented for typeahead

source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h, source/qml/Library/RendererQml/ChoiceSetRender.cpp, source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ChoiceSetRender.qml
=> Added Dynamic Filtered ChoiceSet functionality

source/qml_v2/AdaptiveCardQmlEngine/models/AdaptiveCardModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/AdaptiveCardModel.h, source/qml_v2/AdaptiveCardQmlEngine/qml/AdaptiveCard.qml
=> Implementation of BackgroundImage for BaseAdaptiveCard

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DateInputRenderer.java, source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimeInputRenderer.java, source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/DateInputHandler.java, source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TimeInputHandler.java, source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java
https://github.com/microsoft/Teams-AdaptiveCards-Mobile/issues/80
The AccessibilityManager in text block rendere was retaining a strong reference to the TextView even when we navigate away from the current fragment or activity. This was causing a memory leak as the memory associated with the TextView wasn't being properly released.
To fix the issue, a WeakReference to the TextView was introduced. This allows the garbage collector to reclaim memory from the TextView when it is no longer in use, preventing a memory leak. Also, a mechanism to remove the listener when the TextView is no longer in memory or when it is detached from the window was added, ensuring that we don't have any dangling listeners causing unnecessary memory retention.
In addition to this, we've identified another …
=> Android : ACL memory leak fix

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java
FIX FOR : https://github.com/microsoft/Teams-AdaptiveCards-Mobile/issues/137
Fixed Scaling Issues for Background Bitmaps
This commit includes significant enhancements to the BackgroundImageLoaderAsync.java file, specifically focusing on the scaling of background images.
Key changes include:
- Modification of the getScaleFactorForCover method to return an array of scale factors for both x and y dimensions instead of the maximum of the two. This allows for more precise scaling of the background image.
- Addition of checks to ensure that the scaled width and height of the image are not zero or less. This prevents potential crashes due to invalid bitmap dimensions.
- Update of the resizeBitmapForCover method to use the separate x and y scale factors when scaling the bitmap. This ensures that …
=> [Android]ACL: fix for rendering large background image

source/android/adaptivecards/build.gradle, source/android/build.gradle, source/android/gradle/wrapper/gradle-wrapper.properties
=> [Android]ACL:Fix gradle version to open in studio

source/qml_v2/AdaptiveCardQmlEngine/AdaptiveCardContext.cpp, source/qml_v2/AdaptiveCardQmlEngine/AdaptiveCardContext.h, source/qml_v2/AdaptiveCardQmlEngine/AdaptiveCardQmlTypes.h, source/qml_v2/AdaptiveCardQmlEngine/CMakeLists.txt, source/qml_v2/AdaptiveCardQmlEngine/models/AdaptiveWarning.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/AdaptiveWarning.h, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.h, source/qml_v2/AdaptiveCardQmlEngine/models/TextInputModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/TextInputModel.h, source/qml_v2/AdaptiveCardQmlEngine/qml/AdaptiveCard.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CardConstants.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CollectionItemDelegate.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputErrorMessage.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputFieldClearIcon.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputLabel.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/MultiLineTextInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/SingleLineTextInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TextInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/resourceEngine.qrc, source/qml_v2/AdaptiveCardQmlEngine/utils/AdaptiveCardEnums.h, source/qml_v2/AdaptiveCardQmlEngine/utils/Utils.cpp, source/qml_v2/AdaptiveCardQmlEngine/utils/Utils.h
=> Single Line and Multi Line Input Text

source/android/adaptivecards/build.gradle, source/android/build.gradle, source/android/constants.gradle, source/android/gradle.properties, source/android/gradle/wrapper/gradle-wrapper.properties, source/android/mobile/build.gradle, source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/CustomObjects/Media/SvgImageLoader.java, source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java, source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/RemoteClientConnection.java, source/android/mobilechatapp/build.gradle, source/android/uitestapp/build.gradle
NO issue , only build issues resolved 
Fixed the build issues for dependencies in ACL
- Volley version updated
- Sharp is removed
- Webrtc is removed
- flex is updated
- Added change for removed libs ..  reference has been taken from 
https://github.com/microsoft/Teams-AdaptiveCards-Mobile/blob/main/source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java#L787
2. Existing relevant …
=> [Android]ACL : fix dependency issues

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java, source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
-> Added content description for expanded and collapsed in button
-> Added content description for Image Link
-> https://app.vidcast.io/share/cd14ee07-2200-4372-bfed-8d4876f26943
-> https://app.vidcast.io/share/0a9443d4-5de4-44f2-aa74-872520730f13
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the testing you performed here if you think that it
=> [SPARK-561374][SPARK-561375] Android: Image link does not announce a label, Android: 'Show Card' button does not announce collapsed/expanded state

source/qml_v2/AdaptiveCardQmlEngine/AdaptiveCardQmlTypes.h, source/qml_v2/AdaptiveCardQmlEngine/CMakeLists.txt, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.h, source/qml_v2/AdaptiveCardQmlEngine/models/TimeInputModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/TimeInputModel.h, source/qml_v2/AdaptiveCardQmlEngine/qml/CollectionItemDelegate.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputErrorMessage.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimeInputPopout.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimeInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimeInputTextField.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimePickerListView.qml, source/qml_v2/AdaptiveCardQmlEngine/resourceEngine.qrc, source/qml_v2/AdaptiveCardQmlEngine/utils/AdaptiveCardEnums.h
=> Time Input model based UI

source/qml_v2/AdaptiveCardQmlEngine/AdaptiveCardQmlTypes.h, source/qml_v2/AdaptiveCardQmlEngine/CMakeLists.txt, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.h, source/qml_v2/AdaptiveCardQmlEngine/models/DateInputModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/DateInputModel.h, source/qml_v2/AdaptiveCardQmlEngine/qml/AdaptiveCard.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CardConstants.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CollectionItemDelegate.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/DateInputPopout.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/DateInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/DateInputTextField.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputErrorMessage.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputFieldClearIcon.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/InputLabel.qml, source/qml_v2/AdaptiveCardQmlEngine/resourceEngine.qrc, source/qml_v2/AdaptiveCardQmlEngine/utils/AdaptiveCardEnums.h
=> DateInput UI

source/qml_v2/AdaptiveCardQmlEngine/models/TimeInputModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/TimeInputModel.h, source/qml_v2/AdaptiveCardQmlEngine/qml/InputErrorMessage.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimeInputPopout.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimeInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimeInputTextField.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/TimePickerListView.qml, source/qml_v2/AdaptiveCardQmlEngine/utils/Utils.cpp, source/qml_v2/AdaptiveCardQmlEngine/utils/Utils.h
=> TimeInput with Actual Data

source/qml_v2/AdaptiveCardQmlEngine/AdaptiveCardQmlTypes.h, source/qml_v2/AdaptiveCardQmlEngine/CMakeLists.txt, source/qml_v2/AdaptiveCardQmlEngine/models/ChoiceSetInputModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/ChoiceSetInputModel.h, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.cpp, source/qml_v2/AdaptiveCardQmlEngine/models/CollectionItemModel.h, source/qml_v2/AdaptiveCardQmlEngine/qml/ChoiceSetRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CollectionItemDelegate.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/ComboboxRender.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CustomCheckBox.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/CustomRadioButton.qml, source/qml_v2/AdaptiveCardQmlEngine/qml/ToggleInputRender.qml, source/qml_v2/AdaptiveCardQmlEngine/resourceEngine.qrc, source/qml_v2/AdaptiveCardQmlEngine/utils/AdaptiveCardEnums.h
- # Related Issue
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a …
=> Choice set model based UI

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java, source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
ISSUE: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-591747
**NOTE**: For multiple issues resolved by this PR use the …
=> [SPARK-591747]:Fixed button renderer set state issue  for older API-29
