- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- Fix TextBlock font.family leading to ReferenceError: CiscoSans not defined
> SPARK-216562: Fix TextBlock font.family

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/Utils.cpp
- source/qml/Library/RendererQml/Utils.h
page above.
Added a function that fetches the time format of the user's system which is used to switch between the 12-hour and the 24-hour format InputTime
24 Hour Format
12 Hour Format
2. Existing …
> Fetch System Time Format for InputTime

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SampleColumnSetChoiceSet.json
- source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactTextField.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumnSet.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift
- Added spacing, separator, minHeight, style properties to ColumnSet element
- Fixed FactSet alignment
- Refactored code
> [MacOS] ColumnSet Renderer Properties and other fixes

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/Utils.h
- modified background and font color of ComboBox
> SPARK-216511:Color fix for ComboBox

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Samples/QmlVisualizer/adaptivecard_dark_config.h
- source/qml/Samples/QmlVisualizer/adaptivecard_light_config.h
page above.
Removed line height for textBlock and textRun
Fixed monospace font
TextBlock Light:
TextBlock Dark:
RichTextBlock Light:
RichTextBlock Dark:
With Line Height (Leads to extra space) :
Without Line Height:
1. New unit tests that were added if any. If none were added please add a quick line …
> Text Elements Monospace Font

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
On placing "\n" in the text field of a textRun , it was not getting parsed
This is fixed by replacing the "\n" with &lt;br/&gt; html tag  
Link to JSON: https://adaptivecards.io/samples/FlightDetails.html
1. New unit tests that were added if any. If none were added please add a quick line …
> RichTextBlock Bug

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
TextBlock supports markdown
Limitation: 
- Text doesn't get elided when it exceeds the length of the card, instead it gets chopped abruptly
- maxLines property does not work 
2. …
> Add markdown for TextBlock

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/Utils.cpp
- source/qml/Library/RendererQml/Utils.h
page above.
Handles the following escape sequences for TextBlock and RichTextBlock
- \n
- \r
- \t
- \\\
- \\"
Child Card
3. Manual scenario …
> Escape sequences For TextBlock and RichTextBlock

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift
> [MacOS] FactSet width fix

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetAlignment.json
- source/macos/AdaptiveCards/AdaptiveCards-bridge/AutoGenerated/Models/ACSColumnSet.h
- source/macos/AdaptiveCards/AdaptiveCards-bridge/AutoGenerated/Models/ACSColumnSet.mm
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumnSet.swift
Added horizontal alignment property in columnset and implemented it, and fixed the bug that makes hover on columnset work when selectAction property exists
page above.
Right Alignment
Center Alignment
Left Alignment
1. New unit tests that were …
> [MacOS]Working horizontal alignment and hover for selectAction Columnset

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/Formatter.h
> fix std::optional<int> conversion in Formatter.h 

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionOpenURLRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionShowCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ActionRenderers/ActionSubmitRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextInputRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRButton.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionViewItem.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
Resource Resolver for - 
* iconUrl
* ImageSet
* Input (inline)
> [MacOS] resource resolver for iconUrl and imageSet

- source/macos/AdaptiveCards/AdaptiveCards/Base/ACRImageProperties.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift
* Fix for images with explicit dimensions (Flight card) 
* Fix for breaking images when resource resolver provides dimensions of the image. 
> [macos] minor fix for images with explicit dimensions

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
1. Padding fix for all collection type items
> [MacOS]Padding fix for collection Items

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCollectionView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift
ImageSet now works inside columns with auto property, max size allowed for images is medium image size of hostConfig
BHP card
Agenda Card
Food Order card:
ImageGallery Card:
> [MacOS]ImageSet Working Inside Columns

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift
- source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/RichTextBlockRendererTest.swift
Since there are certain 1.3 properties which are implemented in Mac renderer, to maintain parity with Windows, add flags, to prevent those properties from having any effect.
Removed underline property
Removed labels from inputs
> [MacOS] Added flag to prevent 1.3 properties from rendering

- source/macos/AdaptiveCards/AdaptiveCards/Base/ACRImageProperties.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentHoldingView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ImageRendererTests.swift
1. Fix for extra padding for images when in column set. 
2. Fix for occasional broken images in multiple columns (weather card)
> [MacOS] fix for extra padding in images in columnset

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ColumnSetMinHeight.json
- source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeBackgroundImage.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeContainer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
1. Added min-height for Column-set and container in baseCardElement
2. Added Test Cases for BaseCardElementRenderer
> [MacOS]Min-height fix for ColumnSet

- source/qml/Library/RendererQml/Utils.cpp
page above.
Assertion Failed when date markdown is passed with date before 1970
3. Manual scenario verification if any; ***Do include .gif's …
> TextBlock(Date Markdown) Bug

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Adaptive-card.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/FactSetSample.json
- source/macos/AdaptiveCards/AdaptiveCards/AdaptiveCard.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift
> [MacOS]Hyperlink text working with renderconfig

- source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.h
- source/macos/AdaptiveCards/AdaptiveCards-bridge/BridgeUtils/BridgeTextUtils.mm
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/FactSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/RichTextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift
Create a function which will add style attributes directly in the markdown string instead of the html string.
TextBlock
RichTectBlock
FactSet:
> [MacOS]Text properties directly added to attributed String

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
- source/qml/Library/RendererQml/AdaptiveRenderContext.cpp
- source/qml/Library/RendererQml/AdaptiveRenderContext.h
page above.
- Changed border colors for all input elements and for the card
- Change choiceSet colors
- Fix TextArea placeholder padding
- Change Icon color for Input Number and Action ShowCard
- Remove Bottom Margin when showCard is opened
https://www.figma.com/file/fi0VC0FEmETIHTTWANqMqJ/Native-B-and-Cs?node-id=0%3A1
Input Number Light
Input Number Dark
Input …
> [SPARK-241909] Border Color and Icon changes based on UX (Windows)

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
This PR contains:
* Fixes the case where users need to click multiple times on buttons to trigger their functions
https://user-images.githubusercontent.com/78958353/133756541-73061728-b6b8-4573-bb7c-4eafbba26bc9.mp4
1. New unit tests that were added if any. …
> [Win] Multiple Button Click Bug Fix

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
- source/qml/Samples/QmlVisualizer/samplecardmodel.cpp
- source/qml/Samples/QmlVisualizer/samplecardmodel.h
page above.
Added the disabled state of the Submit Button and enable it 2s after submit action. Done to maintain parity with the UCF adaptive card library
https://user-images.githubusercontent.com/78541663/142005462-ac2a9e7b-82b6-4d3c-8943-e09dde44e5a3.mp4
https://user-images.githubusercontent.com/78541663/142005518-ab3d00e0-4858-4aee-99f7-eeac818dd487.mp4
How you …
> [SPARK-267453] Added Disable State for Submit Button (Windows)

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
page above.
Removed Empty spaces after Cards containing Images
Original             	   |  Updated
2. Existing relevant unit/regression tests …
> Card Image Height

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
[SPARK-227200](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227200]),
[SPARK-227200](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289079)
Clipping not set to true for a Column set. 
Before Fix :
Manual Verification Please find screenshot below :
> Fix for SPARK-289079 & SPARK-227200.

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ErrorMessageInsideContainers.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ErrorMessagesInCard.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ErrorMessagesInColumns.json
- source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRMultilineInputTextView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeChoiceSetInput.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputNumber.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputTime.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputToggle.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextInput.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
> [MacOS] Working ErrorMessage Delegates

- source/macos/AdaptiveCards/AdaptiveCards/Base/BaseProtocol.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ChoiceSetInputRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputToggleRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputToggleRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestHelpers.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRChoiceSetButtonTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRChoiceSetViewTests.swift
page above.
Screen Reader Support for
ChoiceSet Compact
ChoiceSet Expanded
Input.Toggle
At the very least …
> [MacOS] Accessibility improvements for 1.3 elements

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
- source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
- source/qml/Library/RendererQml/AdaptiveRenderContext.cpp
- source/qml/Library/RendererQml/AdaptiveRenderContext.h
- source/qml/Library/RendererQml/ComboBoxRender.cpp
- source/qml/Library/RendererQml/DateInputRender.cpp
- source/qml/Library/RendererQml/TimeInputRender.cpp
- source/qml/Samples/QmlVisualizer/AdaptiveCardItemDelegate.qml
- source/qml/Samples/QmlVisualizer/CardComponent.qml
- source/qml/Samples/QmlVisualizer/QmlVisualizer.vcxproj
- source/qml/Samples/QmlVisualizer/main.cpp
- source/qml/Samples/QmlVisualizer/main.qml
- source/qml/Samples/QmlVisualizer/samplecardmodel.cpp
- source/qml/Samples/QmlVisualizer/samplecardmodel.h
page above.
- Selecting a single text block enabled for Adaptive Cards
How you verified the …
> [Win] Text Select Added to Adaptive Cards

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
- source/qml/Samples/QmlVisualizer/SampleCardJson.h
- source/qml/Samples/QmlVisualizer/samplecardlist.cpp
page above.
Added Center Alignment for Action set in Horizontal Alignment section for Buttons and cards …
> [Win] Buttons and Cards Center Alignment in Action Set 

- source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextBlockRendererTests.swift
Textblock weights do not work with markdown bold and italics
The issues fixed with this PR [SPARK-241471](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-241471).
page above.
- Fixed Markdown with multi traits (Bold and Italic). 
- Fixed Markdown With Monospaced and multi traits.
Original             	   |  Updated
1. New unit tests that were added …
> commit: Fix:: 241471 markdown with bold and italics

- source/macos/AdaptiveCards/AdaptiveCards/Base/ACRImageProperties.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Utils/ImageUtils.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentHoldingView.swift
- Remove the existing imageview setup constraints logic. take help from Microsoft iOS AdaptiveCard imageview class. 
- Fixed ImageView unmanageable constraints.
> Refactor ImageView constraint

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Utils/HostConfigUtils.swift
Markdown indentation was not taking care of tabbing introduced due to ordered list.
Added flow for same.
`{
"type": "AdaptiveCard",
"body": [
{
"type": "TextBlock",
"text": "1. Open the **Cisco AnyConnect Secure Mobility Client** from your Applications folder.\n\n2. Select the closest location. \n\n **Need more guidance?**\n\n[View detailed instructions](https://ontrack-static.cisco.com/Welcome-Mac.pdf) in the Device Portal.",
"wrap": true
}
],
"$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.2"
}`
**old flow**
**new flow**
3. Manual …
> 1. removed redundant styling , 2. added flow for tabbing indent case

- source/qml/Library/RendererQml/TextInputRender.cpp
page above.
- Show the text initially when the card is rendered in Multiline TextEdit
At the very least please …
> Set the Initial Value for MultiLine

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
If column has width property as auto, UI not rendering properly.
To fix that, setting all column with equal width if any one has width property as auto
`{
"$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
"type":"AdaptiveCard",
"version":"1.2",
"body":[
{
"type":"TextBlock",
"text":"Actual Alert",
"wrap":true,
"spacing":"None",
"color":"Attention",
"weight":"Lighter",
"isSubtle":false,
"size":"Default"
},
{
"type":"ColumnSet",
"columns":[
{
"type":"Column",
"items":[
{
"type":"Input.ChoiceSet",
"id":"dropdown",
"value":"I'm on it",
"choices":[
{
"title":"I'm on it",
"value":"I'm on it"
},
{
"title":"No Action Needed",
"value":"No Action Needed"
},
{
"title":"Invalid Alert",
"value":"Invalid Alert"
},
{
"title":"Mass",
"value":"Mass"
}
],
"wrap":true,
"spacing":"None", …
> setting all column with equal width if any one has width property as auto

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/TextInputRender.cpp
- source/qml/Library/RendererQml/TextInputRender.h
> Card Crash for MultiLine Text Edit 1.3

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/TextBlockRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextBlockRendererTests.swift
- TextBlock which contains a numbered or bulletins list indent minor changes
- Add Test case
page above.
At …
> Fixed: [Mac] TextBlock which contains a numbered list does not indent

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.h
- source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
- source/qml/Library/RendererQml/AdaptiveRenderContext.cpp
- source/qml/Library/RendererQml/AdaptiveRenderContext.h
- source/qml/Library/RendererQml/CheckBoxRender.cpp
- source/qml/Library/RendererQml/ChoiceSetRender.cpp
- source/qml/Library/RendererQml/ComboBoxRender.cpp
- source/qml/Library/RendererQml/DateInputRender.cpp
- source/qml/Library/RendererQml/NumberInputRender.cpp
- source/qml/Library/RendererQml/TextInputRender.cpp
- source/qml/Library/RendererQml/TimeInputRender.cpp
- source/qml/Library/RendererQml/ToggleInputRender.cpp
- source/qml/Samples/QmlVisualizer/samplecardmodel.cpp
> Show Card Compiling Delayed and Height Estimate 

- source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/xcshareddata/xcschemes/AdaptiveCardsTests.xcscheme
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
Elements with auto width inside ColumnSet not rendering properly. Issues seems prevalent in input elements (date, time)
Changes done : set the minWidthConstraint for dateField to 100.
Screenshots :
Old :
New:
> width auto elements not rendering properly

- source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
- source/qml/Library/RendererQml/ComboBoxRender.cpp
> Input ChoiceSet Overflow Fixed

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/TestUtils.swift
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ImageCharity.json
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ImageRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- update imagerenderer
- update test case for visibility context
- add json file
**Before**    |  **Updated**
page above.
This information lives with the code and will help future …
> Fix: charity bot image issue

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
page above.
Action Render with only Icon URL Crash Fixed
At the very least please describe the issue you are …
> Action Render Crash Fixed

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/SeparatorNoneTest.json
- source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift
- source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSVisibilityManager.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/SpacingView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeTextBlock.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/BaseCardElementRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/SeparatorNoneTest.json.dataset/Contents.json
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/SeparatorNoneTest.json.dataset/SeparatorNoneTest.json
- change is SpacingView.renderSpacer return nil when separator == None
- add not nil separator scenario at associateSeparatorWithOwner method
- Remove nonretainObject strong reference to weak reference NSView
- handle nil scenario
- Minor changes
page above.
Create a [descriptive title and provide all of the relevant details in the …
> Fixed: ACSFillerManager.getSeparator crash

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/LastElementVisibilityBasicCase.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/LastElementVisibilityInContainer.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/LastElementVisibilityShowCard.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ToggleVisibilityWithMinHeight.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ToggleVisibilityWithoutMinHeight.json
- source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift
- source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSVisibilityManager.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
Toggle Visibility does not work in certain scenarios where there is a min height requirement and all the stretcable views are hidden, forcing a view with fixed size to stretch
| Previous | Current    | 
| :---:   | :---: |
| ![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/78855675/202911512-af64a58f-44ff-4442-9d3c-6b08eb63a9de.gif)  |  ![fix-hide-spike](https://user-images.githubusercontent.com/78855675/202911549-5c0c0415-fbbb-44cd-a709-5af01f17ad5b.gif)  |
| ![image](https://user-images.githubusercontent.com/78855675/202967469-33b1a2a0-6c72-4c29-be08-a8de7dccb824.png) | ![image](https://user-images.githubusercontent.com/78855675/202967506-df84fa6a-c52d-4633-85f8-c610a9e25d0f.pn …
> Stretchable View not working properly at first time after Action.Toggle

- source/macos/AdaptiveCards/AdaptiveCards/Base/ResourceResolverProtocol.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- Add new Image setup protocol at ImageResourceHandlerView
- This change help in calling set the image from the client side as needed, While there are many adaptive cards in table or collection view.
page above.
This information lives …
> Add new protocol at ImageResourceHandlerView for Image setup

- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- bug fix: elements are aligned horizontally according to the image horizontal alignment.
page above.
This information lives with the code and will help …
> Fix:: Elements get center when image is center aligned

- source/qml/Library/RendererQml/ChoiceSetRender.cpp
- source/qml/Library/RendererQml/Utils.cpp
page above.
- Input label was not supporting html special characters, this fix will convert HTML special …
> Input Label Special Character Added

- source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRSingleLineInputTextView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRButtonTests.swift
Fixed inline button getting stretched without title
```{ "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", "type": "AdaptiveCard", "version": "1.3", "body": [ { "type": "Input.Text", "id": "iconInlineActionId", "label": "Text input with an inline action", "inlineAction": { "type": "Action.Submit", "iconUrl": "https://adaptivecards.io/content/send.png" } }, { "type": "Input.Text", "label": "Text input with an inline action with no icon", "id": "textInlineActionId", "inlineAction": { "type": "Action.OpenUrl", "title": "", "url": "https://adaptivecards.io" } }, { "type": "TextBlock", "text": "New TextBlock", "wrap": true }, { "type": "ActionSet", "actions": [ { "type": "Action.Submit", "iconUrl": "https://adaptivecards.io/content/send.png" } ] }, { "type": "ActionSet", …
```
> [macOS] inline button stretch fix without title

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-stretch-with-toggleaction.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/Container-toggle-stretchview.json
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
- update container file
- update and add unit test
page above. …
> Fix: ActionSet height gets ambigus with stretch containers

- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardConstants.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CardGenericTextElement.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ChoiceSetRender.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ComboboxRender.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomCheckBox.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/CustomRadioButton.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ToggleInputRender.qml
page above.
- Added Focus Rings for Choice Set and Input Toggle
- Jira : …
> Focus Rings For Choice Set and Input Toggle

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ErrorElementHiddenSelectAction.json
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceButton.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRChoiceSetCompactPopupButton.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRCompactChoiceSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRInputToggleView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRSingleLineInputTextView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextInputView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputToggle.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputToggleRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/TextInputRedererTest.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRChoiceSetButtonTests.swift
- changes in ACRChoiceButton
- delegate method changes in Input.Toggle
- Input handler change in Input.Text
- ACRTextView regression line changes in ACL
**Before output** | **Changes output**
page above.
Create a [descriptive title and provide all of the relevant details in the …
> macOS | Fix | Error message hidden on submit action

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InvaidDefaultDateTimeSample.json
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputDateRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputTimeRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestHelpers.swift
If the default value provided was beyond the date/time range, user would be able to submit the value, since no checks are done on submit for date/time for min and max. This was resolved here
https://app.vidcast.io/share/70e4cc16-2408-4d02-93e5-f4c91cb2d8f3
Added tests
> [macOS] Fixed Date Time accepting values outside min max range

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/LongPlaceholderAndValue.json
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRFactSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRTextFieldTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
Fixed issue where single line text field does not vertically align if the placeholder/value is too long
Fixed ssue where the textfield cell moves to the left if it gets selected when hidden
Old:
New:
> macOS: Fixed issue with long placeholder/value in single line text fields

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/InputNumberWithExponents.json
- source/macos/AdaptiveCards/AdaptiveCards-bridge/AutoGenerated/Models/ACSNumberInput.mm
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/InputNumberRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/InputNumberRendererTest.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRNumericTextFieldTests.swift
Fixed issue with input number not allowing exponents
Fixed issue to increase max, min and value from int max to double max
Original : Render fails since default value too large
Updated:
> (mac) Fix Input Number Max size issue

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/AdaptiveActionRender.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/ComboboxRender.qml
- source/qml/Samples/QmlVisualizer/AdaptiveCardQml/TextInputRender.qml
> Button Disabled Bug Fix

- source/qml/Library/RendererQml/AdaptiveCardQmlRenderer.cpp
> Bems Adaptive Card Crash Fix

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/RootViewController.swift
- source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSAccessibilityFocusManager.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- Implement logic for handle show card element order with insert pointer head
- Implement logic for handle skip the hidden view and assign immediate next view
- optimise recalculateKeyViewLoop logic
- Implement refocus logic for action.Toggle and show card
For all Pull Requests, please describe how the issue was fixed or how the feature was implemented from a summary level. This information will be used to help provide context to the reviewers of the pull request and should be additive to the issue being closed.
3. Manual scenario verification if any; …
> [macOS] Focus Accessibility: Implement for action ShowCard & Toggle

- source/macos/AdaptiveCards/AdaptiveCards/Views/FlatButton.swift
- add focus ring
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a …
> [macOS][BnC] Fix: Double Focus Ring around ACRButton

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/VerticalContentAlignment1.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/VerticalContentAlignment2.json
- source/macos/AdaptiveCards/AdaptiveCards/Managers/ACSFillerSpaceManager.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
Added support for vertical content alignment
Old:
New:
New tests Added
> [mac] Add Vertical content alignment support with inheritance

- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift
- Change in ACRTextView key down event
page above.
For all Pull Requests, please describe how the issue was fixed or how the feature was implemented from a summary level. This information will be used to help provide context to the reviewers of the pull request and should be additive to the issue being closed.
1. New unit tests that were added if any. If none were added please add a quick line explaining why …
> Fix: [macOS] escape from card when we have focus on any TextView

- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRDateField.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextField.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRTextView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeInputDate.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Views/ACRViewTests.swift
- update MultilineText input
- update Date-Time Input
- update test
page above.
For all Pull Requests, please describe how the issue was fixed or how the feature was implemented from a summary level. This information will be used to help provide context to the reviewers of the pull request and should be additive to the issue being closed.
Original             	   |  Updated
How you verified the fix, including one or …
> [macOS] Fix: Focus goes inside the hidden ShowCard

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/MultipleElemetsInColumSet.json
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/ToggleVisibilityChildToParent.json.dataset/Contents.json
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/ToggleVisibilityChildToParent.json.dataset/ToggleVisibilityChildToParent.json
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/ToggleVisibilityWithMinHeight.json.dataset/Contents.json
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/ToggleVisibilityWithMinHeight.json.dataset/ToggleVisibilityWithMinHeight.json
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/ToggleVisibilityWithoutMinHeight.json.dataset/Contents.json
- source/macos/AdaptiveCards/AdaptiveCardsTests/TestResources.xcassets/ToggleVisibilityWithoutMinHeight.json.dataset/ToggleVisibilityWithoutMinHeight.json
Columnset with all colums having auto width wasn't respecting the auto width property, instead it was forcing each column to have equal width. This has been fixed in the current PR. 
There is an edge case where if there are a large number of columns we still set all columns to have equal width to make sure all elements have some screen real estate at least
Before:
After:
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the testing you performed here if you think that it
will aid in code reviews or corresponding fixes on other platforms …
> macOS: Fix issue With column auto width

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ContainerBleedWithImage.json
- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/ContainerSelectAction.json
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/BaseCardElementRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ColumnSetRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/ContainerRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCards/Utils/BleedUtils.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContainerView.swift
- source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumn.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeColumnSet.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Fakes/FakeContainer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnSetRendererTests.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
- refactor bleed configuration at base render
- add new methods in collection element view
- bug fix
- add new unit test for bleed
page above.
For all Pull Requests, please describe how the issue was fixed or how the feature was implemented from a summary level. This information will be used to help provide context to the reviewers of the pull request and should be additive to the issue being closed.
Before             	   |  Updated
**Bleed Regressions Test** | **
1. New unit tests that were added if any. If none were added please …
> Fix: [macOS] collections element bleeds to bottom of card instead of just the edges

- source/qml/Library/RendererQml/AdaptiveElementRenderers.h
> SPARK-448250_Windows_Webex_app_43.7_crash

- source/qml/Library/RendererQml/NumberInputRender.cpp
> SPARK-443311_Adaptive_Card_inputNumber_wrong_Fixed

- source/macos/ADCMacOSVisualizer/ADCMacOSVisualizer/samples/AssociatedInputNoneInShowCard.json
- source/macos/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
- source/macos/AdaptiveCards/AdaptiveCards/Renderers/AdaptiveCardRenderer.swift
- source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/AdaptiveCardRendererTests.swift
When a card had a show card with a submit button and that submit button had associated input set as none, the submit button would not work. This has been fixed in this PR
RCA: We set the main card to have the messageID as the identifier, but do not set any for the child cards. This is usually not the problem for submitting since normally when we submit the child card passes it's data to main card and thus we use the identifier of main card to validate and send the message. But if the child card's submit has associatedInput set to none, we directly send the action to conversation bypassing the main card, so there is no messageID which fails our check and we do not submit.
To fix this, now all show cards have the same identifier(message ID) as the main card
Added in json list
Added test
> [mac]Fixed bug with associated inputs in show card

- source/macos/AdaptiveCards/AdaptiveCards/Views/SpacingView.swift
> [mac] Fixed issue with seperator

- source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
- source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
-> [SPARK-561375](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-561375)
-> Fix collapsed expanded state for show card button
-> https://app.vidcast.io/share/341b02cd-2194-4189-a228-51bec9c403a3
> [SPARK-561375]: Show Card'button does not announce collapsed/expanded state
